### PR TITLE
[uart] fix UART line-ending

### LINKED ISSUE #5: [log] no return in log output
Log output looks messy due to lack of "returns" in log output. By default configuration, ESP32 will convert "\n" as "\r\n", however, the configuration seems having been reset during the ot-esp32's own UART configuration.

### PR DESCRIPTION
**Pull request by wgtdkp**
This PR disables CRLF conversion in ESP_IDF `vfs/uart` module every time we write radio frame through UART and enables the conversion for CLI UART after finishing writing radio frame. This works because the OpenThread stack is ran in a single task/thread, so there is no CLI operations when we are reading or writing RADIO UART.

addresses issue https://github.com/openthread/ot-esp32/issues/5.

### CODE REVIEW

**Comment by wgtdkp** [comment]
compiling failed, work in progress.

**Comment by wgtdkp** [comment]
@lanyuwen I tested this fix on my linux and macOS machines and both work well, so I think this is prepared to be reviewed. please let me know if this doesn't work within your environment.

**Review by lanyuwen — APPROVED** [review]
LGTM! 👍

File: src/spinel_hdlc.cpp [hunk 1]
```diff
@@ -210,7 +210,14 @@ otError HdlcInterface::Write(const uint8_t *aFrame, uint16_t aLength)
...
     {
-        ssize_t rval = write(mUartFd, aFrame, aLength);
+        ssize_t rval;
+
+        // Configure ESP-IDF UART to never convert "\n" to "\r\n" just before
+        // writing radio frames through UART. This is a workaround for issue:
+        // https://github.com/openthread/ot-esp32/issues/5.
+        esp_vfs_dev_uart_set_tx_line_endings(ESP_LINE_ENDINGS_LF);
+        rval = write(mUartFd, aFrame, aLength);
+        esp_vfs_dev_uart_set_tx_line_endings(ESP_LINE_ENDINGS_CRLF);
```
Comment (lanyuwen) [inline src/spinel_hdlc.cpp:220]: I know this is a temporary workaround, but will it look better to set ESP_LINE_ENDINGS_CRLF/ESP_LINE_ENDINGS_LF every time before/after CLI Uart is written to?

Comment (wgtdkp) [reply src/spinel_hdlc.cpp:220]: It seems possible to do that, will try.

Comment (wgtdkp) [reply src/spinel_hdlc.cpp:220]: @lanyuwen Tried and it seems that changing line-ending configuration for every write at CLI UART requires changing underlying `vprintf` of ESP_LOG as well (ESP_LOG writes to `stdout` and `stderr` which is CLI UART by default). though this is doable with `esp_log_set_vprintf(...)`, but it introduce unnecessary complexity since CLI UART (UART 0) could be shared by more potential components/applications which are out of our control.

So manually configuring RADIO UART seems to be more practical as we own it exclusively.

Comment (lanyuwen) [reply src/spinel_hdlc.cpp:220]: Ok, that's fine to proceed with the original fix if the new proposal introduces too much complexity.

**Review by jwhui — APPROVED** [review]
